### PR TITLE
CP-2084 Release w_module 0.4.0

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [CP-2089 Updated README to use Github raw content url](https://github.com/Workiva/w_module/pull/54)
* [REF-1267 Add suspend / resume semantics](https://github.com/Workiva/w_module/pull/55)
* [CP-2683 Enable strong-mode/linter. Use `@protected` annotation.](https://github.com/Workiva/w_module/pull/56)

Requested by: charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.4...version-bump-w_module-0-4-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.3.4...0.4.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
