### PR TITLE
Revert "Ensure all child modules get unloaded"

### PR DESCRIPTION
**Pull request by dustyholmes-wf**
Reverts Workiva/w_module#239

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by alexandercampbell-wk — APPROVED** [review]
+1

**Comment by alexandercampbell-wk** [comment]
For posterity:
This revert is necessary because (quoting from Dusty's Slack message):
> ~800 test failures in the update…
>[...] Our mock modules do not always emit the didDispose.

**Comment by dustyholmes-wf** [comment]
QA+1

clean revert

This PR is ready for merging @Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
