### PR TITLE
WP-4910 Update LifecycleModule to DisposableManagerV6

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Description

There is a new version of the `DisposableManager` interface that we can update `LifecycleModule` to.

## Testing

- [ ] CI Passes (tests added)

## Code Review
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by georgelesica-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
+10

Things Tested
-------------
- [x] CI Passed

**Comment by bencampbell-wf** [comment]
@jayudey-wf ready for QA.

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - performed and documented by Ben
- [ ] Security review (if required)
- [ ] Unit tests created/updated
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Pull request merged**
