### PR TITLE
AF-2560 module name in operation name

### PR DESCRIPTION
**Pull request by toddbeckman-wf**
# Problem

This isn't helpful:

# Solution

Put the module name in the operation name

# Testing

- [ ] Use the examples to create some traces and verify the operation names contain the module names (printed in dev console)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by georgelesica-wf** [comment]
+1 nice, good idea!

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - passing CI
  - verified in the `Multiple Module Panel` example that the module names were being captured in the spans emitted to the console
- [ ] Security review (if required)
- [ ] Unit tests created/updated
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
