### PR TITLE
CP-1227 cleanup old tooling, w_module

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- add docs badge
- update doc gen tooling

## Changes
**Source:**
- none

**Tests:**
- none

## Areas of Regression
- none

## Testing
- ensure doc gen works

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1 @jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - was still able to successfully generate docs
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
