### PR TITLE
WP-3864 Release w_module 1.2.1

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [WP-3897 Bump lower bound on w_common dependency](https://github.com/Workiva/w_module/pull/78)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.0...version-bump-w_module-1-2-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.0...1.2.1

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
