### PR TITLE
CP-1184 Release w_module 0.3.3

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1184

JIRA and PR's included in this release: 

 CP-1227  - cleanup old tooling, w_module  - https://github.com/Workiva/w_module/pull/45

 CP-1335  - Add DeferredModule transformer, w_module.  - https://github.com/Workiva/w_module/pull/40

======= w_module 0.3.3 items =======

 REF-1068  - Add onDidLoadChildModule and similar methods to LifecycleModule  - https://github.com/Workiva/w_module/pull/48
======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.2...CP-1184_release_0.3.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.3.2...0.3.3

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
