### PR TITLE
CP-1013 Release w_module 0.3.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1013

JIRA and PR's included in this release: 

 CP-1015  - remove all non OSS dependencies  - https://github.com/Workiva/w_module/pull/31
 CP-1019  - update inline doc strings, w_module  - https://github.com/Workiva/w_module/pull/32
 CP-1020  - add license text, w_module  - https://github.com/Workiva/w_module/pull/33
 CP-1026  - add README, w_module  - https://github.com/Workiva/w_module/pull/34
 CP-1031  - fix page load reject in panel example  - https://github.com/Workiva/w_module/pull/35
 CP-1044  - enable public CI, w_module  - https://github.com/Workiva/w_module/pull/36

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.0...CP-1013_release_0.3.1

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
