### PR TITLE
CP-2762 Release w_module 0.4.1

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [MOBILE-2277: Implement serializable w_module](https://github.com/Workiva/w_module/pull/59)
* [CP-2941 Adding smithy.yaml](https://github.com/Workiva/w_module/pull/60)

Requested by: @maxpeterson-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.4.0...version-bump-w_module-0-4-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.4.0...0.4.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
