### PR TITLE
CP-2083 Remove deferred module transformer

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
The deferred module transformer code was merged a long time ago as "alpha". It's largely not an issue since it's isolated to a separate entry point, but I included the transformer in this package's `pubspec.yaml` which forces that transformer on all consumers. This is an issue since the transformer uses dependencies that are only specified in our `dev_dependencies` block.

## Solution
No one is using the deferred module transformer and we've settled on a different approach. It is safe to remove. If we ever want to go back this direction, we'll have it in the history.

## Testing
- [ ] CI passes
- [ ] All references to deferred module transformer removed

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@evanweible-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/78720921/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by rmconsole-wf** [comment]
@evanweible-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/78720921/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by srinivasdhanwada-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
 - no reference to transformer any longer
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
