### PR TITLE
CP-2077 Release w_module 0.3.4

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-2077

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= w_module 0.3.4 items =======

 CP-2083  - Remove deferred module transformer  - https://github.com/Workiva/w_module/pull/51

 CP-2082  - Revert breaking change to LifecycleModule.name  - https://github.com/Workiva/w_module/pull/50

======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.3...CP-2077_release_0.3.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.3.3...0.3.4

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
