### PR TITLE
Test new automated release process

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Summary
This is an empty PR to test the new automated release on every PR merge functionality.
After merge, a new release should be created automatically.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by olesiathoms-wk** [comment]
QA+1 CI passes

**Comment by smaifullerton-wk** [comment]
+10

**Comment by todbachman-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
