### PR TITLE
FEDX-1480: implemented reusable workflows

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
# [FEDX-1480](https://jira.atl.workiva.net/browse/FEDX-1480)
Issue Status

## Motivation
Updated w_module to make use of `gha-dart-oss`

### QA Checklist
- [ ] CI passes should be sufficient

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by evanweible-wf — APPROVED** [review]

**Comment by matthewnitschke-wk** [comment]
QA +1

- [x]  CI does indeed pass

🚀 @Workiva/release-management-p 🚢

**Comment by matthewnitschke-wk** [comment]
Rosie?

@Workiva/release-management-p

**Comment by matthewnitschke-wk** [comment]
🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
