### PR TITLE
CP-3023 Release w_module 1.0.0

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [RAP-1510 Use Enum Value in Noop Warning Message](https://github.com/Workiva/w_module/pull/66)
* [RAP-1482 Mix Disposable into LifecycleModule](https://github.com/Workiva/w_module/pull/62)
* [RAP-1483 Only allow one module load/unload cycle](https://github.com/Workiva/w_module/pull/63)
* [RAP-1484 Enforce LifecycleModule State Transitions](https://github.com/Workiva/w_module/pull/64)
* [RAP-1501 Implement Disposal Via Composition](https://github.com/Workiva/w_module/pull/65)

Requested by: @bencampbell-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.4.1...version-bump-w_module-1-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.4.1...1.0.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by bencampbell-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
Quality Review Approval: +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Pull request merged**
