### PR TITLE
AF-3155 Release w_module 2.0.5

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [Clear child modules on dispose.](https://github.com/Workiva/w_module/pull/139)

Requested by: @greg.littlefield

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.4...Workiva:release_w_module_2.0.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.4...2.0.5

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5416683323785216/logs/)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by greglittlefield-wf** [comment]
+10 @Workiva/release-management-pp

**Comment by greglittlefield-wf** [comment]
Waiting for changelog to merge

**Comment by greglittlefield-wf** [comment]
+10

@Workiva/release-management-pp

**Comment by evanweible-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

@Workiva/release-management-pp

**Pull request merged**
