### PR TITLE
CPLAT-7616: Preparations for React 16 compatibility

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
> __These changes / builds will first be reviewed by a member of the Client Platform team.__ 
> 
> Repo owners will be notified when it is ready for additional review, merge and release.

## Motivation
Wdesk is currently using ReactJS `15.6.1` _(released on June 14, 2017)_, and the Client Platform team 
has been working to upgrade our Dart wrappers to be compatible with the latest major version of ReactJS (`16.x`). 
Now that major releases of the `react` (`5.0.0`) and `over_react` (`3.0.0`) packages have laid the foundation
for ReactJS 16 compatibility, __its time to begin making the entire Workiva front-end
ecosystem compatible!__

__But Why?__
The ReactJS `16.0.0` release included an internal rewrite that set the stage for some new features, 
ranging from new and improved APIs for authoring UI, to a new "concurrent mode" that improves performance 
_and perceived performance_ of Web applications.

Keeping React up-to-date and supporting its latest features — particularly those being introduced in the `16.x` line — 
will help us be more efficient at writing, maintaining, and optimizing our UIs.

## Changes
1. Raise the upper bounds of the `react` / `over_react` dependencies to allow the new major release versions to be pulled in once all downstream dependencies are also compatible.
2. Prepare code for React 16 via minor codemod updates. 
  1. All changes/fixes will be handled by Client Platform before repo owners are requested for review(s).
  2. Certain changes cannot be made automatically, but the codemod will add comments in the code for these cases. 
    1. The Client Platform team will go through and manually verify these edge-cases, and update the comment in a way that will ensure the [React 16 core check](https://wiki.atl.workiva.net/display/CP/Rollout+Plan#RolloutPlan-CoreCheck) will not fail moving forward. 
    
      __Please do not modify / remove these comments!__

#### Release Notes
Make this library compatible with ReactJS 16. 

## Review
Please review: @greglittlefield-wf @aaronlademann-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk

### QA Checklist
- [ ] Passing CI

__NOTE:__ Manual React 16 testing should be done using #158 - not this branch.
  
> [More information about the React 16 upgrade](https://wiki.atl.workiva.net/pages/viewpage.action?spaceKey=CP&title=React+16)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by aaronlademann-wf** [comment]
@Workiva/release-management-pp

**Comment by aaronlademann-wf** [comment]
+1

**Comment by greglittlefield-wf** [comment]
+1

**Pull request merged**
