### PR TITLE
WP-3239 Release w_module 1.1.0

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [RAP-1529 Do not allow loadChildModule calls when unloading or unloaded](https://github.com/Workiva/w_module/pull/68)
* [RAP-1628 Create simple module API.](https://github.com/Workiva/w_module/pull/69)
* [WP-3662 : added docs.yml](https://github.com/Workiva/w_module/pull/70)
* [RAP-1679 Stream Lifecycle Method Errors](https://github.com/Workiva/w_module/pull/71)

Requested by: @jayudey-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.0.0...version-bump-w_module-1-1-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.0.0...1.1.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by bencampbell-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
