### PR TITLE
CPLAT-5758 Release w_module 2.0.8

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [CPLAT-6708: Add stack trace to more logs](https://github.com/Workiva/w_module/pull/151)
	* [CPLAT-6710: Add missing module name override](https://github.com/Workiva/w_module/pull/152)
	* [CPLAT-6851: Add disposable type name(s)](https://github.com/Workiva/w_module/pull/153)

Requested by: @olesiathoms-wk

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.7...Workiva:release_w_module_2.0.8
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.7...2.0.8

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5416683323785216/logs/)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by olesiathoms-wk** [comment]
QA +1 CI passes

**Comment by olesiathoms-wk** [comment]
QA+1 CI passes

**Comment by olesiathoms-wk** [comment]
@Workiva/release-management-pp

**Comment by georgelesica-wf** [comment]
+1 @Workiva/release-management-p

**Pull request merged**
