### PR TITLE
WP-3905 Release w_module 1.2.2

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [RAP-1850 Await Loading, Suspending, and Resuming State Transitions](https://github.com/Workiva/w_module/pull/81)

Requested by: @bencampbell-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.1...version-bump-w_module-1-2-2_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.1...1.2.2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
@jayudey-wf ready for you!

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
