### PR TITLE
WP-3662 : added docs.yml

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
### Description

We would like this readme in the dev portal

### Changes

Added docs.yml

### Semantic Versioning

- [x] **Patch**
  - [x] This change does not affect the public API
  - [ ] This change fixes existing incorrect behavior without any additions
- [ ] **Minor**
  - [ ] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
- [ ] **Major**
  - [ ] This change removes part of the public API that was deprecated in a
        previous major version

### Testing/QA

- [ ] CI passes

### Code Review

@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@Workiva/devtools-pp

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jayudey-wf** [comment]
do we want oss repo's to have a docs.yml?

**Comment by nickmiller-wf** [comment]
+1 on docs.yml. I personally don't have any problem sharing out the docs.yml publicly

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1, docs change only

Merging into master

**Pull request merged**
