### PR TITLE
CP-1174 Add Child Modules Getter to LifecycleModule

### PR DESCRIPTION
**Pull request by todbachman-wf**
## Problem:
It would be helpful to have a getter to access the `_childModules` list that is maintained by the `LifecycleModule`. Specifically, as someone who is extending the `LifecycleModule` it would be nice to not have to maintain my own list of child modules when it's already being managed by the parent class.

## Solution:
Added a getter that exposes the `_childModules` list as an `Iterable<LifecycleModule>`.

## Possible Areas of Regression:
None -- this is just the introduction of a getter property for an existing field.

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
Looks good. Would be nice to add a unit test or maybe just an assertion to an existing unit test to ensure `.childModules` returns an Iterable of the expected module instances.

**Comment by todbachman-wf** [comment]
@maxwellpeterson-wf. Good point! A unit test is incoming...

**Comment by timmccall-wf** [comment]
+1 from me

**Comment by evanweible-wf** [comment]
Once #41 gets merged, this will need to be rebased against master and then the build should pass.

**Comment by trentgrover-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1 again
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - passing CI with unit text exercising new functionality
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
