### PR TITLE
RAP-2220 Update Module to the latest DisposableManager interface

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue

`LifecycleModule` supports memory management by proxying to an underlying disposable instead of extending `Disposable` directly. It is currently implementing V3 but the latest version is V5.

## Solution

Update `LifecycleModule` to update the latest version of the disposable manager interface: `DisposableManagerV5`.

## Testing

- [ ] CI passes (tests updated)

> It would be nice if there was a `w_common_tests` package that provided a test suite that exercises classes that implement the `DisposableManager` interfaces so that we could get these verifications for free.

## Code Review
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by maxwellpeterson-wf** [comment]
+10
- CI passes

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Tests created/updated 
- [x] All tests pass

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
