### PR TITLE
AF-1387 Remove dart:mirrors & SerializableModule

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Overview
Dart 2 removes dart:mirrors support when compiled to JS. So we're removing usage of dart:mirrors
This is a **breaking change** since it is a removal of multiple publicly exposed classes. 

The only affected consumers are updated. (w_viewer and w_viewer_mobile.)
PRs are https://github.com/Workiva/w_viewer/pull/528 and https://github.com/Workiva/w_viewer_mobile/pull/32

### Release plan (remove breaking change risk)
 - [x] Review, merge, and tag w_viewer major version 9.0.0
 - [x] Consume w_viewer 9 in w_viewer_mobile
 - [x] Release w_viewer_mobile
 - [x] Release mobile apps

### Remove dart:mirrors from product lines + unified (unblock dart 2)
 - [ ] Review, merge this PR
 - [ ] Tag w_module 2.0
 - [ ] Consume w_module 2.0 in all tier 1 projects

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by todbachman-wf** [comment]
Why is serializable module being removed?

**Comment by robbecker-wf** [comment]
SerializableModule is only used for the mobile viewer https://github.com/search?q=org%3AWorkiva+SerializableModule&type=Code .. I'm spiking out reimplementing that native/dart bridging without reflection in https://github.com/Workiva/w_viewer_mobile/pull/32 and https://github.com/Workiva/w_viewer/pull/528

**Comment by jayudey-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
+10
  - code intended to be removed (which constitutes a breaking change, which this has been marked as) was

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
  - https://github.com/Workiva/w_module/pull/113#issuecomment-421172553
- [ ] Tests created/updated 
  - code removal only
- [x] All tests pass

@Workiva/release-management-pp

**Comment by robbecker-wf** [comment]
+1 on Max's commits

**Pull request merged**
